### ISSUE TITLE
Android - Does not compile with proguard

### ISSUE THREAD

**Issue by angel9306** [urbanairship/android-samples#18]
the library sends a compilation error with proguard.

I found this link does not work:
http://docs.urbanairship.com/reference/libraries/android/latest/reference/com/urbanairship/Autopilot.html

**Comment by hcrowell** [comment]
Hi @angel9306 ,

Please try the link again, we were able to view it with no issues:
 http://docs.urbanairship.com/reference/libraries/android/latest/reference/com/urbanairship/Autopilot.html

If your app uses Proguard obfuscation, you will need to add an exclusion to proguard.cfg for your Autopilot class:
`-keep public class * extends com.urbanairship.Autopilot`

If the above suggestion does not resolve the issue, please pass this on to support@urbanairship.com with any more info you have that will help us investigate: library version, full compilation error/report, device models/OS versions affected, etc.

Thanks!
