### ISSUE TITLE
UAirship.shared().getPushManager().getChannelId() always return null

### ISSUE THREAD

**Issue by minturandhir** [urbanairship/android-samples#19]
In push sample app I am getting channelId null always.

```
private void updateChannelIdField() {
        String channelIdString = UAirship.shared().getPushManager().getChannelId();
        Log.e("","My Application Channel ID: " + channelIdString);
        channelIdString = UAStringUtil.isEmpty(channelIdString) ? "" : channelIdString;

        // fill in channel ID text
        if (!channelIdString.equals(channelID.getText())) {
            channelID.setText(channelIdString);
        }
    }
```

output 

`E/﹕ My Application Channel ID: null`

**Comment by rlepinski** [comment]
Channel registration is an asynchronous operation that requires a network connection. Also, before the SDK starts the channel registration process it tries to register with GCM.  If the channel might not be available right away, but eventually should be created. The sample app will automatically responds to the channel creation and display the channel on the home screen.  It sounds like it might not be happening for you so if you were to check the logs and see if anything stands out such as channel registration failed,  gcm registration failed, etc...

If you can, please post your logs here. Before doing so, remove any app credentials.

**Comment by rlepinski** [comment]
Closing now. This is most likely a config issue.
